
[workspace]
members = [
    "core",
    "protos",
    "cli",
    #"coins/bitcoin",
    "coins/ethereum",
]

[patch.crates-io]
trezor-client = { path = "./core" }
trezor-protos = { path = "./protos" }
